window.KasorraSeedData = {
  popularSearches: [
    "cement bags",
    "corrugated boxes",
    "coconut sugar",
    "motherboards",
    "sample orders",
    "escrow suppliers",
    "verified packaging",
  ],
  categories: [
    {
      id: "construction",
      name: "Construction",
      description: "Materials, hardware, fixtures, and site supplies.",
      subcategories: ["Cement", "Steel", "Lumber", "Tiles", "Safety Gear"],
    },
    {
      id: "packaging",
      name: "Packaging",
      description: "Retail, food, shipping, and sustainable packaging.",
      subcategories: ["Corrugated Boxes", "Flexible Pouches", "Labels", "Eco Wraps", "Glass Jars"],
    },
    {
      id: "food-ingredients",
      name: "Food Ingredients",
      description: "Bulk ingredients, staples, flavorings, and specialty inputs.",
      subcategories: ["Rice", "Coconut Products", "Meat", "Produce", "Sweeteners"],
    },
    {
      id: "tech-components",
      name: "Tech Components",
      description: "Electronics parts, boards, sensors, and repair inventory.",
      subcategories: ["Motherboards", "Connectors", "Sensors", "Power Modules", "Displays"],
    },
  ],
  suppliers: [
    {
      id: "luzon-buildworks",
      companyName: "Luzon BuildWorks Supply",
      logo: "images/shield4.png",
      location: "Bulacan, Philippines",
      description: "SEC-registered construction distributor serving contractors and hardware chains across Luzon.",
      verified: true,
      verificationType: "SEC",
      escrowEnabled: true,
      rating: 4.8,
      reviewCount: 142,
      yearsActive: 9,
      categories: ["construction", "packaging"],
      reviews: [
        "Consistent cement quality and fast trucking schedule.",
        "Quotation team replies quickly for repeat project orders.",
      ],
    },
    {
      id: "greenwrap-industries",
      companyName: "GreenWrap Industries",
      logo: "images/package.png",
      location: "Cavite, Philippines",
      description: "DTI-verified packaging manufacturer focused on recyclable food-safe cartons, pouches, and labels.",
      verified: true,
      verificationType: "DTI",
      escrowEnabled: true,
      rating: 4.7,
      reviewCount: 98,
      yearsActive: 6,
      categories: ["packaging", "food-ingredients"],
      reviews: [
        "Good print registration on custom cartons.",
        "Sample packs helped us validate sizing before the bulk run.",
      ],
    },
    {
      id: "mindanao-ingredients",
      companyName: "Mindanao Ingredients Co.",
      logo: "images/ricey.png",
      location: "Davao, Philippines",
      description: "Bulk food ingredient supplier for bakeries, commissaries, and food processors.",
      verified: true,
      verificationType: "SEC",
      escrowEnabled: false,
      rating: 4.6,
      reviewCount: 116,
      yearsActive: 12,
      categories: ["food-ingredients", "packaging"],
      reviews: [
        "Stable quality for coconut sugar and rice flour.",
        "Helpful documentation for food safety requirements.",
      ],
    },
    {
      id: "techsource-pro",
      companyName: "TechSource Pro Components",
      logo: "images/motherboards.avif",
      location: "Metro Manila, Philippines",
      description: "Distributor of board-level components, repair inventory, and industrial electronics parts.",
      verified: true,
      verificationType: "SEC",
      escrowEnabled: true,
      rating: 4.9,
      reviewCount: 211,
      yearsActive: 8,
      categories: ["tech-components"],
      reviews: [
        "Accurate stock counts and packed safely.",
        "RFQ negotiation was transparent and easy to track.",
      ],
    },
  ],
  products: [
    {
      id: "cement-bag-40kg",
      supplierId: "luzon-buildworks",
      name: "Portland Cement 40kg Bags",
      description: "General purpose Portland cement for commercial builds and hardware resale.",
      categories: ["construction"],
      subcategory: "Cement",
      moq: 100,
      sampleMoq: 5,
      price: 238,
      availability: "In stock",
      specs: ["40kg per bag", "Type 1P", "Palletized loading", "Delivery within Luzon"],
      mediaUrl: "images/industrial.jpg",
      mediaType: "image",
      popular: true,
    },
    {
      id: "steel-rebar-10mm",
      supplierId: "luzon-buildworks",
      name: "10mm Deformed Steel Rebar",
      description: "Grade 40 rebars for slab, column, and beam reinforcement.",
      categories: ["construction"],
      subcategory: "Steel",
      moq: 250,
      sampleMoq: 10,
      price: 142,
      availability: "Limited stock",
      specs: ["6m length", "Grade 40", "Bundle pricing", "Mill certificate available"],
      mediaUrl: "images/wew.png",
      mediaType: "image",
      popular: false,
    },
    {
      id: "custom-corrugated-box",
      supplierId: "greenwrap-industries",
      name: "Custom Corrugated Shipping Box",
      description: "Made-to-size shipping cartons with optional one-color print and food-safe liner options.",
      categories: ["packaging"],
      subcategory: "Corrugated Boxes",
      moq: 500,
      sampleMoq: 25,
      price: 18,
      availability: "Made to order",
      specs: ["B-flute board", "Custom die-line", "One-color print", "7-day sample lead time"],
      mediaUrl: "images/packaging.webp",
      mediaType: "image",
      popular: true,
    },
    {
      id: "standup-kraft-pouch",
      supplierId: "greenwrap-industries",
      name: "Kraft Stand-Up Pouch",
      description: "Resealable kraft pouch for dry food, coffee, and powdered ingredients.",
      categories: ["packaging", "food-ingredients"],
      subcategory: "Flexible Pouches",
      moq: 1000,
      sampleMoq: 50,
      price: 9,
      availability: "In stock",
      specs: ["250g and 500g sizes", "Food-grade liner", "Zipper seal", "Window option"],
      mediaUrl: "images/package.png",
      mediaType: "image",
      popular: true,
    },
    {
      id: "coconut-sugar-bulk",
      supplierId: "mindanao-ingredients",
      name: "Organic Coconut Sugar",
      description: "Bulk coconut sugar for bakeries, beverage brands, and private-label food producers.",
      categories: ["food-ingredients"],
      subcategory: "Sweeteners",
      moq: 50,
      sampleMoq: 2,
      price: 185,
      availability: "In stock",
      specs: ["25kg sack", "Organic farm source", "Food safety documents", "Amber granules"],
      mediaUrl: "images/foo.webp",
      mediaType: "image",
      popular: true,
    },
    {
      id: "jasmine-rice-flour",
      supplierId: "mindanao-ingredients",
      name: "Jasmine Rice Flour",
      description: "Fine-milled rice flour for noodles, bakery mixes, and gluten-free product lines.",
      categories: ["food-ingredients"],
      subcategory: "Rice",
      moq: 80,
      sampleMoq: 5,
      price: 72,
      availability: "In stock",
      specs: ["20kg bag", "Fine mesh", "Batch COA available", "Wholesale pallet rates"],
      mediaUrl: "images/rice.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "industrial-motherboard-kit",
      supplierId: "techsource-pro",
      name: "Industrial Motherboard Kit",
      description: "Board kit for repair shops and embedded systems integrators.",
      categories: ["tech-components"],
      subcategory: "Motherboards",
      moq: 20,
      sampleMoq: 1,
      price: 2850,
      availability: "In stock",
      specs: ["Mini-ITX", "I/O shield included", "Warranty tested", "Bulk serial tracking"],
      mediaUrl: "images/motherboards.avif",
      mediaType: "image",
      popular: true,
    },
    {
      id: "waterproof-sensor-pack",
      supplierId: "techsource-pro",
      name: "Waterproof Sensor Connector Pack",
      description: "Connector packs for industrial sensor replacements and IoT field deployments.",
      categories: ["tech-components", "construction"],
      subcategory: "Connectors",
      moq: 100,
      sampleMoq: 10,
      price: 46,
      availability: "In stock",
      specs: ["IP67 rated", "3-pin and 4-pin variants", "Bulk trays", "Datasheet included"],
      mediaUrl: "images/electronics.jpg",
      mediaType: "image",
      popular: false,
    },
  ],
};
