window.KasorraSeedData = {
  popularSearches: [
    "cement bags",
    "corrugated boxes",
    "coconut sugar",
    "motherboards",
    "sample orders",
    "escrow suppliers",
    "verified packaging",
  ],
  categories: [
    {
      id: "construction",
      name: "Construction",
      description: "Materials, hardware, fixtures, and site supplies.",
      subcategories: ["Cement", "Steel", "Lumber", "Tiles", "Safety Gear"],
    },
    {
      id: "packaging",
      name: "Packaging",
      description: "Retail, food, shipping, and sustainable packaging.",
      subcategories: ["Corrugated Boxes", "Flexible Pouches", "Labels", "Eco Wraps", "Glass Jars"],
    },
    {
      id: "food-ingredients",
      name: "Food Ingredients",
      description: "Bulk ingredients, staples, flavorings, and specialty inputs.",
      subcategories: ["Rice", "Coconut Products", "Meat", "Produce", "Sweeteners"],
    },
    {
      id: "tech-components",
      name: "Tech Components",
      description: "Electronics parts, boards, sensors, and repair inventory.",
      subcategories: ["Motherboards", "Connectors", "Sensors", "Power Modules", "Displays"],
    },
  ],
  suppliers: [
    {
      id: "luzon-buildworks",
      companyName: "Luzon BuildWorks Supply",
      logo: "images/shield4.png",
      location: "Bulacan, Philippines",
      description: "SEC-registered construction distributor serving contractors and hardware chains across Luzon.",
      verified: true,
      verificationType: "SEC",
      escrowEnabled: true,
      rating: 4.8,
      reviewCount: 142,
      yearsActive: 9,
      categories: ["construction", "packaging"],
      reviews: [
        "Consistent cement quality and fast trucking schedule.",
        "Quotation team replies quickly for repeat project orders.",
      ],
    },
    {
      id: "greenwrap-industries",
      companyName: "GreenWrap Industries",
      logo: "images/package.png",
      location: "Cavite, Philippines",
      description: "DTI-verified packaging manufacturer focused on recyclable food-safe cartons, pouches, and labels.",
      verified: true,
      verificationType: "DTI",
      escrowEnabled: true,
      rating: 4.7,
      reviewCount: 98,
      yearsActive: 6,
      categories: ["packaging"],
      reviews: [
        "Good print registration on custom cartons.",
        "Sample packs helped us validate sizing before the bulk run.",
      ],
    },
    {
      id: "mindanao-ingredients",
      companyName: "Mindanao Ingredients Co.",
      logo: "images/ricey.png",
      location: "Davao, Philippines",
      description: "Bulk food ingredient supplier for bakeries, commissaries, and food processors.",
      verified: true,
      verificationType: "SEC",
      escrowEnabled: false,
      rating: 4.6,
      reviewCount: 116,
      yearsActive: 12,
      categories: ["food-ingredients", "packaging"],
      reviews: [
        "Stable quality for coconut sugar and rice flour.",
        "Helpful documentation for food safety requirements.",
      ],
    },
    {
      id: "techsource-pro",
      companyName: "TechSource Pro Components",
      logo: "images/motherboards.avif",
      location: "Metro Manila, Philippines",
      description: "Distributor of board-level components, repair inventory, and industrial electronics parts.",
      verified: true,
      verificationType: "SEC",
      escrowEnabled: true,
      rating: 4.9,
      reviewCount: 211,
      yearsActive: 8,
      categories: ["tech-components"],
      reviews: [
        "Accurate stock counts and packed safely.",
        "RFQ negotiation was transparent and easy to track.",
      ],
    },
    {
      id: "cebu-industrial-traders",
      companyName: "Cebu Industrial Traders",
      logo: "images/package.png",
      location: "Cebu, Philippines",
      description: "Regional wholesaler onboarding to Kasorra with mixed construction, packaging, ingredient, and component inventory.",
      verified: false,
      verificationType: "Pending",
      escrowEnabled: false,
      rating: 4.1,
      reviewCount: 27,
      yearsActive: 3,
      categories: ["construction", "packaging", "food-ingredients", "tech-components"],
      reviews: [
        "Good starter pricing while their verification is being completed.",
        "Responsive on sample requests, but payment terms need review.",
      ],
    },
  ],
  products: [
    {
      id: "cement-bag-40kg",
      supplierId: "luzon-buildworks",
      name: "Portland Cement 40kg Bags",
      description: "General purpose Portland cement for commercial builds and hardware resale.",
      categories: ["construction"],
      subcategory: "Cement",
      moq: 100,
      sampleMoq: 5,
      price: 238,
      availability: "In stock",
      specs: ["40kg per bag", "Type 1P", "Palletized loading", "Delivery within Luzon"],
      mediaUrl: "images/products/cement-bags.jpg",
      mediaType: "image",
      popular: true,
    },
    {
      id: "steel-rebar-10mm",
      supplierId: "luzon-buildworks",
      name: "10mm Deformed Steel Rebar",
      description: "Grade 40 rebars for slab, column, and beam reinforcement.",
      categories: ["construction"],
      subcategory: "Steel",
      moq: 250,
      sampleMoq: 10,
      price: 142,
      availability: "Limited stock",
      specs: ["6m length", "Grade 40", "Bundle pricing", "Mill certificate available"],
      mediaUrl: "images/products/rebar-bundles.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "marine-plywood-18mm",
      supplierId: "luzon-buildworks",
      name: "18mm Marine Plywood Sheets",
      description: "Moisture-resistant plywood sheets for formworks, cabinets, and interior build-outs.",
      categories: ["construction"],
      subcategory: "Lumber",
      moq: 60,
      sampleMoq: 2,
      price: 920,
      availability: "In stock",
      specs: ["4ft x 8ft", "18mm thickness", "Phenolic glue", "Bulk pallet loading"],
      mediaUrl: "images/products/plywood-panels.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "ceramic-floor-tile-60x60",
      supplierId: "luzon-buildworks",
      name: "60x60 Ceramic Floor Tile",
      description: "Matte ceramic tile for residential, commercial, and fit-out projects.",
      categories: ["construction"],
      subcategory: "Tiles",
      moq: 80,
      sampleMoq: 4,
      price: 68,
      availability: "In stock",
      specs: ["60cm x 60cm", "Matte finish", "Boxed by 4 pieces", "Slip-resistant surface"],
      mediaUrl: "images/products/ceramic-tiles.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "safety-helmet-set",
      supplierId: "cebu-industrial-traders",
      name: "Construction Safety Helmet Set",
      description: "Adjustable hard hats for contractors, site visitors, and warehouse teams.",
      categories: ["construction"],
      subcategory: "Safety Gear",
      moq: 120,
      sampleMoq: 6,
      price: 155,
      availability: "In stock",
      specs: ["ABS shell", "Adjustable harness", "White, yellow, and blue", "Logo print option"],
      mediaUrl: "images/products/safety-helmets.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "galvanized-roofing-sheet",
      supplierId: "luzon-buildworks",
      name: "Galvanized Roofing Sheet",
      description: "Corrugated roofing sheets for warehouses, sheds, and light industrial buildings.",
      categories: ["construction"],
      subcategory: "Steel",
      moq: 75,
      sampleMoq: 3,
      price: 410,
      availability: "Made to order",
      specs: ["0.4mm gauge", "Custom cut length", "Zinc-coated", "Bundled delivery"],
      mediaUrl: "images/products/roofing-sheet.png",
      mediaType: "image",
      popular: false,
    },
    {
      id: "pvc-conduit-20mm",
      supplierId: "cebu-industrial-traders",
      name: "20mm PVC Electrical Conduit",
      description: "Rigid conduit pipes for commercial electrical rough-ins and fit-out projects.",
      categories: ["construction"],
      subcategory: "Safety Gear",
      moq: 300,
      sampleMoq: 20,
      price: 38,
      availability: "In stock",
      specs: ["20mm diameter", "3m length", "Flame-retardant PVC", "Couplers available"],
      mediaUrl: "images/products/pvc-conduit.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "ready-mix-mortar",
      supplierId: "luzon-buildworks",
      name: "Ready-Mix Masonry Mortar",
      description: "Bagged mortar mix for masonry, patching, and small contractor jobs.",
      categories: ["construction"],
      subcategory: "Cement",
      moq: 100,
      sampleMoq: 5,
      price: 182,
      availability: "In stock",
      specs: ["25kg bag", "Pre-blended mix", "Consistent setting time", "Hardware resale ready"],
      mediaUrl: "images/products/cement-bags.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "anchor-bolt-m12",
      supplierId: "cebu-industrial-traders",
      name: "M12 Expansion Anchor Bolt",
      description: "Heavy-duty anchor bolts for structural fixtures, racks, and machinery bases.",
      categories: ["construction"],
      subcategory: "Steel",
      moq: 500,
      sampleMoq: 25,
      price: 24,
      availability: "In stock",
      specs: ["M12 x 100mm", "Zinc-plated", "Boxed by 50", "Pull test documents on request"],
      mediaUrl: "images/products/anchor-bolt.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "fiberglass-insulation-roll",
      supplierId: "luzon-buildworks",
      name: "Fiberglass Insulation Roll",
      description: "Thermal and acoustic insulation rolls for warehouses, roofs, and commercial interiors.",
      categories: ["construction"],
      subcategory: "Lumber",
      moq: 50,
      sampleMoq: 2,
      price: 520,
      availability: "In stock",
      specs: ["1.2m x 10m roll", "Foil-faced option", "Fire-retardant", "Compressed packing"],
      mediaUrl: "images/products/insulation.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "custom-corrugated-box",
      supplierId: "greenwrap-industries",
      name: "Custom Corrugated Shipping Box",
      description: "Made-to-size shipping cartons with optional one-color print and food-safe liner options.",
      categories: ["packaging"],
      subcategory: "Corrugated Boxes",
      moq: 500,
      sampleMoq: 25,
      price: 18,
      availability: "Made to order",
      specs: ["B-flute board", "Custom die-line", "One-color print", "7-day sample lead time"],
      mediaUrl: "images/products/corrugated-boxes.jpg",
      mediaType: "image",
      popular: true,
    },
    {
      id: "standup-kraft-pouch",
      supplierId: "greenwrap-industries",
      name: "Kraft Stand-Up Pouch",
      description: "Resealable kraft pouch for dry food, coffee, and powdered ingredients.",
      categories: ["packaging"],
      subcategory: "Flexible Pouches",
      moq: 1000,
      sampleMoq: 50,
      price: 9,
      availability: "In stock",
      specs: ["250g and 500g sizes", "Food-grade liner", "Zipper seal", "Window option"],
      mediaUrl: "images/packaging.webp",
      mediaType: "image",
      popular: true,
    },
    {
      id: "paperboard-folding-carton",
      supplierId: "greenwrap-industries",
      name: "Paperboard Folding Carton",
      description: "Retail folding cartons for cosmetics, dry food, supplements, and small consumer goods.",
      categories: ["packaging"],
      subcategory: "Corrugated Boxes",
      moq: 700,
      sampleMoq: 25,
      price: 14,
      availability: "Made to order",
      specs: ["350gsm board", "Custom dieline", "Matte lamination option", "Flat-packed delivery"],
      mediaUrl: "images/products/paperboard-cartons.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "printed-product-label",
      supplierId: "greenwrap-industries",
      name: "Waterproof Printed Product Label",
      description: "Roll labels for bottles, jars, pouches, and retail cartons.",
      categories: ["packaging"],
      subcategory: "Labels",
      moq: 1000,
      sampleMoq: 50,
      price: 3,
      availability: "Made to order",
      specs: ["Gloss or matte", "Waterproof adhesive", "Custom die cut", "CMYK print"],
      mediaUrl: "images/products/product-labels.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "compostable-mailer-bag",
      supplierId: "greenwrap-industries",
      name: "Compostable Courier Mailer",
      description: "Plant-based mailing bags for apparel, cosmetics, and lightweight retail shipments.",
      categories: ["packaging"],
      subcategory: "Eco Wraps",
      moq: 800,
      sampleMoq: 40,
      price: 12,
      availability: "In stock",
      specs: ["12 x 16 inch", "Self-seal strip", "Opaque finish", "Custom print available"],
      mediaUrl: "images/packaging.webp",
      mediaType: "image",
      popular: false,
    },
    {
      id: "glass-jar-250ml",
      supplierId: "greenwrap-industries",
      name: "250ml Food Glass Jar",
      description: "Clear glass jars for sauces, spreads, pickles, and pantry retail lines.",
      categories: ["packaging"],
      subcategory: "Glass Jars",
      moq: 600,
      sampleMoq: 24,
      price: 22,
      availability: "In stock",
      specs: ["250ml capacity", "Metal lug cap", "Food-safe glass", "Tray-packed"],
      mediaUrl: "images/products/glass-jar.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "pulp-food-tray",
      supplierId: "cebu-industrial-traders",
      name: "Molded Pulp Food Tray",
      description: "Compostable trays for commissaries, meal prep brands, and food courts.",
      categories: ["packaging"],
      subcategory: "Eco Wraps",
      moq: 1200,
      sampleMoq: 50,
      price: 7,
      availability: "In stock",
      specs: ["Sugarcane pulp", "Three-compartment option", "Microwave-safe", "Carton packed"],
      mediaUrl: "images/products/pulp-tray.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "thermal-shipping-liner",
      supplierId: "greenwrap-industries",
      name: "Thermal Insulated Shipping Liner",
      description: "Insulated box liners for chilled food, pharma samples, and temperature-sensitive parcels.",
      categories: ["packaging"],
      subcategory: "Corrugated Boxes",
      moq: 300,
      sampleMoq: 10,
      price: 31,
      availability: "Made to order",
      specs: ["Foil bubble liner", "Custom box fit", "Cold-chain use", "Flat-packed"],
      mediaUrl: "images/products/corrugated-boxes.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "bopp-packing-tape",
      supplierId: "cebu-industrial-traders",
      name: "BOPP Carton Sealing Tape",
      description: "Clear and printed packing tape for warehouses and fulfillment centers.",
      categories: ["packaging"],
      subcategory: "Labels",
      moq: 240,
      sampleMoq: 12,
      price: 42,
      availability: "In stock",
      specs: ["48mm x 100m", "Acrylic adhesive", "Clear or brown", "Logo print option"],
      mediaUrl: "images/products/corrugated-boxes.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "vacuum-seal-bag",
      supplierId: "greenwrap-industries",
      name: "Food Vacuum Seal Bag",
      description: "Embossed vacuum pouches for meat, seafood, produce, and frozen goods.",
      categories: ["packaging"],
      subcategory: "Flexible Pouches",
      moq: 1500,
      sampleMoq: 100,
      price: 5,
      availability: "In stock",
      specs: ["Nylon PE film", "Multiple sizes", "Freezer-safe", "Heat-seal compatible"],
      mediaUrl: "images/packaging.webp",
      mediaType: "image",
      popular: false,
    },
    {
      id: "coconut-sugar-bulk",
      supplierId: "mindanao-ingredients",
      name: "Organic Coconut Sugar",
      description: "Bulk coconut sugar for bakeries, beverage brands, and private-label food producers.",
      categories: ["food-ingredients"],
      subcategory: "Sweeteners",
      moq: 50,
      sampleMoq: 2,
      price: 185,
      availability: "In stock",
      specs: ["25kg sack", "Organic farm source", "Food safety documents", "Amber granules"],
      mediaUrl: "images/products/coconut-sugar.jpg",
      mediaType: "image",
      popular: true,
    },
    {
      id: "jasmine-rice-flour",
      supplierId: "mindanao-ingredients",
      name: "Jasmine Rice Flour",
      description: "Fine-milled rice flour for noodles, bakery mixes, and gluten-free product lines.",
      categories: ["food-ingredients"],
      subcategory: "Rice",
      moq: 80,
      sampleMoq: 5,
      price: 72,
      availability: "In stock",
      specs: ["20kg bag", "Fine mesh", "Batch COA available", "Wholesale pallet rates"],
      mediaUrl: "images/products/rice-flour.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "desiccated-coconut-fine",
      supplierId: "mindanao-ingredients",
      name: "Fine Desiccated Coconut",
      description: "Unsweetened desiccated coconut for bakeries, snack makers, and ingredient repackers.",
      categories: ["food-ingredients"],
      subcategory: "Coconut Products",
      moq: 60,
      sampleMoq: 3,
      price: 156,
      availability: "In stock",
      specs: ["25kg bag", "Fine grade", "Low moisture", "Food safety documents"],
      mediaUrl: "images/products/coconut.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "frozen-chicken-breast",
      supplierId: "cebu-industrial-traders",
      name: "Frozen Chicken Breast Fillet",
      description: "IQF chicken breast fillets for commissaries, restaurants, and processors.",
      categories: ["food-ingredients"],
      subcategory: "Meat",
      moq: 100,
      sampleMoq: 5,
      price: 198,
      availability: "Limited stock",
      specs: ["2kg packs", "Halal option", "Cold-chain delivery", "COA on request"],
      mediaUrl: "images/products/chicken-fillet.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "banana-puree-drum",
      supplierId: "mindanao-ingredients",
      name: "Banana Puree Drum",
      description: "Bulk banana puree for beverage, bakery, and baby food manufacturing.",
      categories: ["food-ingredients"],
      subcategory: "Produce",
      moq: 20,
      sampleMoq: 1,
      price: 1480,
      availability: "Made to order",
      specs: ["200kg drum", "Aseptic packed", "No added sugar", "Batch traceability"],
      mediaUrl: "images/products/banana-puree.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "cane-molasses-bulk",
      supplierId: "mindanao-ingredients",
      name: "Food-Grade Cane Molasses",
      description: "Rich cane molasses for sauces, fermentation, bakery, and feed-adjacent processors.",
      categories: ["food-ingredients"],
      subcategory: "Sweeteners",
      moq: 30,
      sampleMoq: 2,
      price: 690,
      availability: "In stock",
      specs: ["25kg pail", "Food-grade", "Dark syrup", "Brix documented"],
      mediaUrl: "images/products/molasses.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "native-corn-starch",
      supplierId: "mindanao-ingredients",
      name: "Native Corn Starch",
      description: "Fine starch for sauces, snacks, bakery mixes, and food processing applications.",
      categories: ["food-ingredients"],
      subcategory: "Rice",
      moq: 100,
      sampleMoq: 5,
      price: 64,
      availability: "In stock",
      specs: ["25kg sack", "Fine powder", "Neutral flavor", "Food processor ready"],
      mediaUrl: "images/products/corn-starch.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "dried-mango-dice",
      supplierId: "cebu-industrial-traders",
      name: "Dried Mango Dice",
      description: "Diced dried mango pieces for cereal, trail mix, bakery, and confectionery lines.",
      categories: ["food-ingredients"],
      subcategory: "Produce",
      moq: 40,
      sampleMoq: 2,
      price: 420,
      availability: "In stock",
      specs: ["10kg carton", "6mm dice", "Low moisture", "Private label ready"],
      mediaUrl: "images/products/dried-mango.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "coconut-milk-powder",
      supplierId: "mindanao-ingredients",
      name: "Coconut Milk Powder",
      description: "Spray-dried coconut milk powder for beverage mixes, sauces, and bakery products.",
      categories: ["food-ingredients"],
      subcategory: "Coconut Products",
      moq: 50,
      sampleMoq: 2,
      price: 275,
      availability: "In stock",
      specs: ["20kg bag", "High fat content", "Dairy-free", "Batch COA available"],
      mediaUrl: "images/products/coconut-milk-powder.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "beef-tapa-marinade",
      supplierId: "cebu-industrial-traders",
      name: "Bulk Beef Tapa Marinade",
      description: "Ready-to-use sweet savory marinade for meat processors and commissaries.",
      categories: ["food-ingredients"],
      subcategory: "Meat",
      moq: 25,
      sampleMoq: 1,
      price: 310,
      availability: "Made to order",
      specs: ["20L pail", "Shelf-stable", "Custom flavor adjustment", "Food service pack"],
      mediaUrl: "images/products/marinade.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "industrial-motherboard-kit",
      supplierId: "techsource-pro",
      name: "Industrial Motherboard Kit",
      description: "Board kit for repair shops and embedded systems integrators.",
      categories: ["tech-components"],
      subcategory: "Motherboards",
      moq: 20,
      sampleMoq: 1,
      price: 2850,
      availability: "In stock",
      specs: ["Mini-ITX", "I/O shield included", "Warranty tested", "Bulk serial tracking"],
      mediaUrl: "images/motherboards.avif",
      mediaType: "image",
      popular: true,
    },
    {
      id: "waterproof-sensor-pack",
      supplierId: "techsource-pro",
      name: "Waterproof Sensor Connector Pack",
      description: "Connector packs for industrial sensor replacements and IoT field deployments.",
      categories: ["tech-components"],
      subcategory: "Connectors",
      moq: 100,
      sampleMoq: 10,
      price: 46,
      availability: "In stock",
      specs: ["IP67 rated", "3-pin and 4-pin variants", "Bulk trays", "Datasheet included"],
      mediaUrl: "images/products/circuit-board.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "industrial-temp-sensor",
      supplierId: "techsource-pro",
      name: "Industrial Temperature Sensor",
      description: "Digital temperature sensor modules for equipment monitoring and IoT deployments.",
      categories: ["tech-components"],
      subcategory: "Sensors",
      moq: 80,
      sampleMoq: 5,
      price: 138,
      availability: "In stock",
      specs: ["-40C to 125C", "Digital output", "Cable assembly option", "Datasheet included"],
      mediaUrl: "images/products/proximity-sensor.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "dc-dc-buck-module",
      supplierId: "techsource-pro",
      name: "DC-DC Buck Converter Module",
      description: "Step-down power modules for repair kits, prototypes, and industrial control panels.",
      categories: ["tech-components"],
      subcategory: "Power Modules",
      moq: 120,
      sampleMoq: 10,
      price: 84,
      availability: "In stock",
      specs: ["5A output", "Adjustable voltage", "Bulk anti-static trays", "QC tested"],
      mediaUrl: "images/products/buck-converter.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "oled-display-128x64",
      supplierId: "techsource-pro",
      name: "128x64 OLED Display Module",
      description: "Compact OLED screens for embedded devices, repair shops, and maker kits.",
      categories: ["tech-components"],
      subcategory: "Displays",
      moq: 100,
      sampleMoq: 5,
      price: 96,
      availability: "In stock",
      specs: ["0.96 inch", "I2C interface", "Blue or white pixel", "ESD packed"],
      mediaUrl: "images/products/tft-display.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "usb-c-port-replacement",
      supplierId: "cebu-industrial-traders",
      name: "USB-C Port Replacement Pack",
      description: "Bulk replacement ports for device repair centers and electronics workshops.",
      categories: ["tech-components"],
      subcategory: "Connectors",
      moq: 300,
      sampleMoq: 20,
      price: 18,
      availability: "In stock",
      specs: ["Type-C female", "Board-mount", "Packed by 100", "Repair-grade inventory"],
      mediaUrl: "images/products/usb-c-socket.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "raspberry-compatible-carrier",
      supplierId: "techsource-pro",
      name: "Raspberry Pi Carrier Board",
      description: "Industrial carrier board for compact automation, kiosks, and edge devices.",
      categories: ["tech-components"],
      subcategory: "Motherboards",
      moq: 30,
      sampleMoq: 1,
      price: 1240,
      availability: "Limited stock",
      specs: ["DIN rail option", "GPIO breakout", "Dual power input", "Warranty tested"],
      mediaUrl: "images/products/raspberry-pi-board.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "lithium-bms-board",
      supplierId: "techsource-pro",
      name: "Lithium Battery BMS Board",
      description: "Battery management boards for repair, solar accessories, and backup power products.",
      categories: ["tech-components"],
      subcategory: "Power Modules",
      moq: 100,
      sampleMoq: 8,
      price: 175,
      availability: "In stock",
      specs: ["3S and 4S variants", "Overcurrent protection", "Anti-static packaging", "Datasheet included"],
      mediaUrl: "images/products/bms-board.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "proximity-sensor-module",
      supplierId: "cebu-industrial-traders",
      name: "Inductive Proximity Sensor Module",
      description: "Sensor modules for automation counters, conveyor lines, and repair inventories.",
      categories: ["tech-components"],
      subcategory: "Sensors",
      moq: 80,
      sampleMoq: 5,
      price: 210,
      availability: "In stock",
      specs: ["NPN output", "12V to 24V", "M12 housing", "Cable included"],
      mediaUrl: "images/products/proximity-sensor.jpg",
      mediaType: "image",
      popular: false,
    },
    {
      id: "tft-display-2-8",
      supplierId: "techsource-pro",
      name: "2.8 Inch TFT Display",
      description: "Color TFT modules for control panels, test rigs, and embedded product builds.",
      categories: ["tech-components"],
      subcategory: "Displays",
      moq: 60,
      sampleMoq: 3,
      price: 340,
      availability: "Made to order",
      specs: ["320x240 resolution", "SPI interface", "Touch option", "Protective tray packing"],
      mediaUrl: "images/products/tft-display.jpg",
      mediaType: "image",
      popular: false,
    },
  ],
};
